title: jekyll Hacker
email: aravindswami135@gmail.com
description: >-
  Jekyll hacker theme test site
domain: cipherswami.github.io
url: https://cipherswami.github.io/
baseurl:
github: [metadata]

# Build settings
markdown: kramdown
theme: jekyll-theme-hacker
